### ISSUE TITLE
Swift gRPC support

### ISSUE THREAD

**Issue by upamune** [znly/docker-protobuf#20]
Hello,

I want to use `protoc-gen-swiftgrpc` for gRPC Swift, but I don't know how to use it on this image.
Is it possible ?

**Comment by Nalum** [comment]
@upamune did you get this working? Looking in the container there is a symlink to `protoc-gen-swiftgrpc` but it links to a file that doesn't exist and doesn't appear to be generated anywhere in the docker file.

I've also looked in the swift build container and cannot find it there.
