### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by magick93** [znly/docker-protobuf#26]
Hello

When I try to build I am getting the following error:

```
docker build .  
Sending build context to Docker daemon  645.6kB
Step 1/52 : FROM alpine:3.6 as protoc_builder
invalid reference format
```
I am using Docker version 17.04.0-ce, build 4845c56.

Do I need a special version of Docker to build?

Thanks

**Comment by steeve** [comment]
You need Docker >=17.05 to use multi stage builds:
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

Other than that, `docker build .` should do fine.

**Comment by magick93** [comment]
Yes, I upgraded docker and can now build
